### ISSUE TITLE
error Unity 

### ISSUE THREAD

**Issue by catafest** [keijiro/KinoMotion#2]
I got this error on running Test-Runner scene: 
I used personal Unity version 5.4.0b13... I try to test your source code.
_I want to see all your script but first I show this , because is need time and work to parse all._

Assets/Kino/Motion/Motion.cs(160,98): error CS0117: `UnityEngine.DepthTextureMode' does not contain a definition for`MotionVectors'

also the Mono develop IDE told me: 
            cb.Blit(null, rtMask, m, 2);  
got error with this IDE image:
![err](https://cloud.githubusercontent.com/assets/2210118/15682411/331193b2-2766-11e6-94c8-cb085aa11382.png)

**Comment by catafest** [comment]
**working well with Unity 5.4.0 Beta 19.**
